
name: 2.work flows events

on: 
    push:
    pull_request:
    # schedule:
    # - cron: '*/10 * * * *'  # Every 10 minutes

    workflow_dispatch:




jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger 
              run: echo "I have been triggered by a(n) ${{ github.event_name }} event."



